# Generated by Django 3.2.3 on 2021-05-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200904_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=210, verbose_name='Nombre'),
        ),
    ]
